#!/usr/bin/env bash
APP=$1
SANDBOXING_OPTION=$2
if [[ -z $CONTAINER_ID ]]; then
  echo "No \$CONTAINER_ID set, you are most likely not running within a container. Exiting."
  exit 1
fi
# set the shared folder
if [[ -d $HOME/Public ]]; then
  SHARED_DIR=$HOME/Public
elif [[ -d $HOME/Общедоступные ]]; then
  SHARED_DIR=$HOME/Общедоступные
else
  echo "no suitable shared dir. exiting"
  exit 2
fi
if [[ ! -d $HOME/container_homes/$CONTAINER_ID ]]; then
  mkdir -p $HOME/container_homes/$CONTAINER_ID
fi

# selector
clear
if [[ $SANDBOXING_OPTION == "" ]]; then
  echo -e "what do ya want\n\t1. regular sandbox\n\t2. no inet\n\t3. no sudo\n\t4. no inet and no sudo"

  read x
else
  x=$SANDBOXING_OPTION
fi

case $x in
"1")
  EXTRA_SANDBOX_OPTS=
  ;;
"2")
  EXTRA_SANDBOX_OPTS="-pPrivateNetwork=yes"
  ;;
"3")
  EXTRA_SANDBOX_OPTS="-pNoNewPrivileges=yes"
  ;;
"4")
  EXTRA_SANDBOX_OPTS="-pNoNewPrivileges=yes -pPrivateNetwork=yes"
  ;;
*)
  echo "what"
  sleep 1
  exit 69
  ;;
esac
if [[ $APP == "" ]]; then
  APP=$SHELL
fi
USER_ID=$(id -u)
XAUTH=$(find /run/user/$USER_ID -name "xauth*" 2>/dev/null)
cd $HOME && exec sudo systemd-run --same-dir --pty --wait --collect --service-type=exec -pUser=$USER_ID -pPrivateTmp=yes -pInaccessiblePaths=/run/host -pBindPaths=/home/$USER/container_homes/$CONTAINER_ID:/var/home/$USER\ /usr/bin/bash:/usr/bin/distrobox-host-exec\ /home/$USER/container_homes/$CONTAINER_ID:/home/$USER\ $SHARED_DIR:$SHARED_DIR\ /run/host/run/user/$USER_ID:/run/user/$USER_ID --setenv=XAUTHORITY=$XAUTH --setenv=DISPLAY=$DISPLAY --setenv=XDG_RUNTIME_DIR=/run/user/$USER_ID $EXTRA_SANDBOX_OPTS $APP
